export const TODO_TYPES = {
  ADD_UPDATE: "ADD_UPDATE",
  ADD_UPDATE_INIT: "ADD_UPDATE_INIT",
  ADD_UPDATE_SUCCESS: "ADD_UPDATE_SUCCESS",
  ADD_UPDATE_FINISH: "ADD_UPDATE_FINISH",

  DELETE: "DELETE",
  DELETE_INIT: "DELETE_INIT",
  DELETE_SUCCESS: "DELETE_SUCCESS",
  DELETE_FINISH: "DELETE_FINISH",

  MARK_AS_COMPLETE: "MARK_AS_COMPLETE",
  MARK_AS_COMPLETE_INIT: "MARK_AS_COMPLETE_INIT",
  MARK_AS_COMPLETE_SUCCESS: "MARK_AS_COMPLETE_SUCCESS",
  MARK_AS_COMPLETE_FINISH: "MARK_AS_COMPLETE_FINISH",
};

export const GLOBAL = {
  GLOBAL_ERROR: "GLOBAL_ERROR",
};
